// This file is autogenerated, do not edit.
// Instead modify generate_definitions.py

`ifndef WARP_DEFINES
`define WARP_DEFINES

`define PIPELINE_XARITH 3'h0
`define PIPELINE_XLOGIC 3'h1
`define PIPELINE_XSHIFT 3'h2
`define PIPELINE_XMULTL 3'h3
`define PIPELINE_XMULTH 3'h4
`define PIPELINE_XDIV   3'h5

`define XARITH_OP_ADD 2'h0
`define XARITH_OP_SLT 2'h1
`define XARITH_OP_CMP 2'h2

`define XLOGIC_OP_AND 3'h0
`define XLOGIC_OP_OR  3'h1
`define XLOGIC_OP_XOR 3'h2
`define XLOGIC_OP_SHF 3'h3
`define XLOGIC_OP_SLA 3'h4
`define XLOGIC_OP_CLZ 3'h5
`define XLOGIC_OP_CTZ 3'h6
`define XLOGIC_OP_POP 3'h7

`define AHB_HTRANS_IDLE   2'h0
`define AHB_HTRANS_BUSY   2'h1
`define AHB_HTRANS_NONSEQ 2'h2
`define AHB_HTRANS_SEQ    2'h3

`define RVFI_METADATA_INPUTS(i) \
	input  wire        if_valid_``i, \
	input  wire [63:0] if_order_``i, \
	input  wire [31:0] if_insn_``i, \
	input  wire        if_trap_``i, \
	input  wire        if_halt_``i, \
	input  wire        if_intr_``i, \
	input  wire [ 1:0] if_mode_``i, \
	input  wire [ 1:0] if_ixl_``i

`define RVFI_METADATA_REGS(i) \
	reg         rf_valid_``i, \
	reg  [63:0] rf_order_``i, \
	reg  [31:0] rf_insn_``i, \
	reg         rf_trap_``i, \
	reg         rf_halt_``i, \
	reg         rf_intr_``i, \
	reg  [ 1:0] rf_mode_``i, \
	reg  [ 1:0] rf_ixl_``i

`define RVFI_METADATA_OUTPUTS(i) \
	output wire        of_valid_``i, \
	output wire [63:0] of_order_``i, \
	output wire [31:0] of_insn_``i, \
	output wire        of_trap_``i, \
	output wire        of_halt_``i, \
	output wire        of_intr_``i, \
	output wire [ 1:0] of_mode_``i, \
	output wire [ 1:0] of_ixl_``i

`define RVFI_PC_INPUTS(i) \
	input  wire [63:0] if_pc_rdata_``i, \
	input  wire [63:0] if_pc_wdata_``i

`define RVFI_PC_REGS(i) \
	reg  [63:0] rf_pc_rdata_``i, \
	reg  [63:0] rf_pc_wdata_``i

`define RVFI_PC_OUTPUTS(i) \
	output wire [63:0] of_pc_rdata_``i, \
	output wire [63:0] of_pc_wdata_``i

`define RVFI_REG_INPUTS(i) \
	input  wire [ 4:0] if_rs1_addr_``i, \
	input  wire [ 4:0] if_rs2_addr_``i, \
	input  wire [63:0] if_rs1_rdata_``i, \
	input  wire [63:0] if_rs2_rdata_``i, \
	input  wire [ 4:0] if_rd_addr_``i, \
	input  wire [63:0] if_rd_wdata_``i

`define RVFI_REG_REGS(i) \
	reg  [ 4:0] rf_rs1_addr_``i, \
	reg  [ 4:0] rf_rs2_addr_``i, \
	reg  [63:0] rf_rs1_rdata_``i, \
	reg  [63:0] rf_rs2_rdata_``i, \
	reg  [ 4:0] rf_rd_addr_``i, \
	reg  [63:0] rf_rd_wdata_``i

`define RVFI_REG_OUTPUTS(i) \
	output wire [ 4:0] of_rs1_addr_``i, \
	output wire [ 4:0] of_rs2_addr_``i, \
	output wire [63:0] of_rs1_rdata_``i, \
	output wire [63:0] of_rs2_rdata_``i, \
	output wire [ 4:0] of_rd_addr_``i, \
	output wire [63:0] of_rd_wdata_``i

`define CANONICAL_NOP 32'h00000013
`define BUNDLE_SIZE 68

`endif /* WARP_DEFINES */
