// This file is autogenerated, do not edit.
// Instead modify generate_definitions.py

`ifndef WARP_DEFINES
`define WARP_DEFINES

`define PIPELINE_XARITH 3'h0
`define PIPELINE_XLOGIC 3'h1
`define PIPELINE_XSHIFT 3'h2
`define PIPELINE_XMULTL 3'h3
`define PIPELINE_XMULTH 3'h4
`define PIPELINE_XDIV   3'h5

`define XARITH_OP_ADD 2'h0
`define XARITH_OP_SLT 2'h1
`define XARITH_OP_CMP 2'h2

`define XLOGIC_OP_AND 3'h0
`define XLOGIC_OP_OR  3'h1
`define XLOGIC_OP_XOR 3'h2
`define XLOGIC_OP_SHF 3'h3
`define XLOGIC_OP_SLA 3'h4
`define XLOGIC_OP_CLZ 3'h5
`define XLOGIC_OP_CTZ 3'h6
`define XLOGIC_OP_POP 3'h7

`define AHB_HTRANS_IDLE   2'h0
`define AHB_HTRANS_BUSY   2'h1
`define AHB_HTRANS_NONSEQ 2'h2
`define AHB_HTRANS_SEQ    2'h3

`define RVFI_METADATA_INPUTS(i) \
	input  wire        if_valid``i, \
	input  wire [63:0] if_order``i, \
	input  wire [31:0] if_insn``i, \
	input  wire        if_trap``i, \
	input  wire        if_halt``i, \
	input  wire        if_intr``i, \
	input  wire [ 1:0] if_mode``i, \
	input  wire [ 1:0] if_ixl``i

`define RVFI_METADATA_REGS(i) \
	reg         rf_valid``i, \
	reg  [63:0] rf_order``i, \
	reg  [31:0] rf_insn``i, \
	reg         rf_trap``i, \
	reg         rf_halt``i, \
	reg         rf_intr``i, \
	reg  [ 1:0] rf_mode``i, \
	reg  [ 1:0] rf_ixl``i

`define RVFI_METADATA_OUTPUTS(i) \
	output wire        of_valid``i, \
	output wire [63:0] of_order``i, \
	output wire [31:0] of_insn``i, \
	output wire        of_trap``i, \
	output wire        of_halt``i, \
	output wire        of_intr``i, \
	output wire [ 1:0] of_mode``i, \
	output wire [ 1:0] of_ixl``i

`define RVFI_PC_INPUTS(i) \
	input  wire [63:0] if_pc_rdata``i, \
	input  wire [63:0] if_pc_wdata``i

`define RVFI_PC_REGS(i) \
	reg  [63:0] rf_pc_rdata``i, \
	reg  [63:0] rf_pc_wdata``i

`define RVFI_PC_OUTPUTS(i) \
	output wire [63:0] of_pc_rdata``i, \
	output wire [63:0] of_pc_wdata``i

`define RVFI_REG_INPUTS(i) \
	input  wire [ 4:0] if_rs1_addr``i, \
	input  wire [ 4:0] if_rs2_addr``i, \
	input  wire [63:0] if_rs1_rdata``i, \
	input  wire [63:0] if_rs2_rdata``i, \
	input  wire [ 4:0] if_rd_addr``i, \
	input  wire [63:0] if_rd_wdata``i

`define RVFI_REG_REGS(i) \
	reg  [ 4:0] rf_rs1_addr``i, \
	reg  [ 4:0] rf_rs2_addr``i, \
	reg  [63:0] rf_rs1_rdata``i, \
	reg  [63:0] rf_rs2_rdata``i, \
	reg  [ 4:0] rf_rd_addr``i, \
	reg  [63:0] rf_rd_wdata``i

`define RVFI_REG_OUTPUTS(i) \
	output wire [ 4:0] of_rs1_addr``i, \
	output wire [ 4:0] of_rs2_addr``i, \
	output wire [63:0] of_rs1_rdata``i, \
	output wire [63:0] of_rs2_rdata``i, \
	output wire [ 4:0] of_rd_addr``i, \
	output wire [63:0] of_rd_wdata``i

`define CANONICAL_NOP 32'h00000013
`define BUNDLE_SIZE 108

`define XSHIFT_OP_SHL 2'b00
`define XSHIFT_OP_SHR 2'b01
`define XSHIFT_OP_ROL 2'b10
`define XSHIFT_OP_ROR 2'b11

`endif
